name: MysteryTeams
version: 1.0
description: EXSolo's MT Plugin
author: EXSolo
main: com.exsoloscript.mysteryteams.MysteryTeamsPlugin
database: false
commands:
  mt:
    description: MT Command
    aliases: mysteryteams