name: MysteryTeams
version: 0.1
description: EXSolo's MT Plugin
author: EXSolo
main: com.exsoloscript.mysteryteams.MysteryTeams
database: false
commands:
  mt:
    description: MT Command
    aliases: mysteryteams